name: tecnoshopping
description: A new Flutter project.
version: 1.0.0+1
environment:
  sdk: '>=2.12.0 <3.0.0'
dependencies:
  cached_network_image: ^3.3.0
  connectivity_plus: ^5.0.2
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.4.0
  flutter_svg: ^2.0.9
  intl: ^0.18.0
  open_file: ^3.3.2
  provider: ^6.1.2
  syncfusion_flutter_pdf: ^25.1.40

flutter_native_splash:
  android: true
  ios: true
  web: false

  color: "#000000"
  image: "assets/images/logoSplash.png"

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
  fonts:
    - family: Raleway
      fonts:
        - asset: assets/fonts/RalewayMedium.ttf
          weight: 500
        - asset: assets/fonts/RalewayRegular.ttf
          weight: 400
        - asset: assets/fonts/RalewaySemiBold.ttf
          weight: 600
        - asset: assets/fonts/RalewayRomanBold.ttf
          weight: 700
        - asset: assets/fonts/RalewayRomanMedium.ttf
          weight: 500
        - asset: assets/fonts/RalewayRomanRegular.ttf
          weight: 400
